### ISSUE TITLE
Argument order of factory methods has been changed in v0.10.0

### ISSUE THREAD

**Issue by unarist** [exoego/aws-lambda-scalajs-facade#179]
For example, APIGatewayProxyResult factory method has below signature in v0.9.0:

https://github.com/exoego/aws-lambda-scalajs-facade/blob/82ed72e0d2efd59669008b66bc3274030456681c/src/main/scala/net/exoego/facade/aws_lambda/apigateway_proxy.scala#L78-L86

and it has been changed to this in v0.10.0 (decompiled with IDEA):

```
object APIGatewayProxyResult extends scala.AnyRef {
  type Headers = net.exoego.facade.aws_lambda.HeadersBDS
  type MultiValueHeaders = net.exoego.facade.aws_lambda.MultiValueHeadersBDS
  @scala.inline
  def apply(body : _root_.scala.Predef.String, statusCode : scala.Double, headers : scala.scalajs.js.UndefOr[net.exoego.facade.aws_lambda.APIGatewayProxyResult.Headers] = { /* compiled code */ }, isBase64Encoded : scala.scalajs.js.UndefOr[scala.Boolean] = { /* compiled code */ }, multiValueHeaders : scala.scalajs.js.UndefOr[net.exoego.facade.aws_lambda.APIGatewayProxyResult.MultiValueHeaders] = { /* compiled code */ }) : net.exoego.facade.aws_lambda.APIGatewayProxyResult = { /* compiled code */ }
}
```

I want to clarify if this is intended change or not, because it wasn't mentioned in the release note.

**Comment by exoego** [comment]
The change was intended.
Factory methods are now generated by macro, and arguments are sorted alphabetically.
Consider using named arguments to avoid the change of arguments order, at least for mandatory arguments.
