### ISSUE TITLE
Bug: CloudFrontRequestEventRecordItem/CloudFrontResponseEventRecordItem facade

### ISSUE THREAD

**Issue by Asamsig** [exoego/aws-lambda-scalajs-facade#183]
Hi, super awesome job creating a complete facade for all the AWS service!

While using the facade for a Lambda@Edge function, I noticed the CloudFrontResponseEventRecordItem/CloudFrontResponseEventRecordItem facades, have a minor bug.

[This facade](https://github.com/exoego/aws-lambda-scalajs-facade/blob/master/src/main/scala/net/exoego/facade/aws_lambda/cloudfront_request.scala#L16) vs [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b9b6b0e9bd5de6ed18be0a3e07816f60fe6f2cfa/types/aws-lambda/trigger/cloudfront-request.d.ts#L14)

As you can see CloudFrontRequestEventRecordItem, should have one field called `cf`, and that field should then be the `CloudFrontRequestEventRecordItem`-object.

I'm hoping to submit a PR shortly!

**Comment by exoego** [comment]
This was fixed in [v0.11.0](https://github.com/exoego/aws-lambda-scalajs-facade/releases/tag/v0.11.0).
