### ISSUE TITLE
0.12.0 is not actually released

### ISSUE THREAD

**Issue by oswaldo** [exoego/aws-lambda-scalajs-facade#335]
Hello, I'm experimenting with this library and following the readme I got a "sbt.librarymanagement.ResolveException: Error downloading net.exoego:aws-lambda-scalajs..."
Although github shows 0.12.0 as the latest release, the artifact doesn't seem to be available, as it isn't even listed in scaladex:
https://index.scala-lang.org/exoego/aws-lambda-scalajs-facade/aws-lambda-scalajs-facade/

**Comment by exoego** [comment]
Thanks.
It turned out that releasing of 0.12.0 failed 😅 
0.12.1 released for Scala 2.13 and 3.x today 🙇
