### ISSUE TITLE
Compile error when extending native JS trait APIGatewayProxyHandler 

### ISSUE THREAD

**Issue by cornerman** [exoego/aws-lambda-scalajs-facade#83]
I am trying to use this facade, but get a compile error when using the example code from the readme:

```
[error] /home/cornerman/projects/dodo/api/src/main/scala/dodo/api/Handler.scala:7:8: A Scala.js-defined JS object cannot directly extend a native JS trait.
[error] object MyFirstLambda extends APIGatewayProxyHandler {
[error]        ^
[error] /home/cornerman/projects/dodo/api/src/main/scala/dodo/api/Handler.scala:11:16: A Scala.js-defined JavaScript class cannot declare a method named `apply` without `@JSName`
[error]   override def apply(event: APIGatewayEvent, contet: Context, callback: Callback[ProxyResult]): Unit | Promise[APIGatewayProxyResult]
[error]                ^
[error] two errors found
```

If I remove the recommended scalajs setting `scalacOptions += "-P:scalajs:sjsDefinedByDefault"`, it compiles but with warnings (regarding this will not work in scalajs 1.0). How is this meant to work?

**Comment by exoego** [comment]
Thanks for the report !!
I did not aware of the situation, since I was only using this facade in earilier Scala.js 0.6 without "-P:scalajs:sjsDefinedByDefault".
PR #84 will address the issue and I will publish a new release within a few days.

**Comment by cornerman** [comment]
Perfect! Thank you!

**Comment by exoego** [comment]
@cornerman 
Released in https://github.com/exoego/aws-lambda-scalajs-facade/releases/tag/v0.5.0
Hope new release fixes the issue !
